# Generated by Django 4.2.7 on 2023-11-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
